### ISSUE TITLE
err.showDiff = true breaks string diffs

### ISSUE THREAD

**Issue by felixrabe** [mochajs/mocha#1241]
Observed:

    2)  should compare strings (raw):

        Error: bad stuff
        + expected - actual

        +"a\nb\nc\nd"
        -"a\nb\n"

Wanted:

    2)  should compare strings (raw):

        Error: bad stuff
        + expected - actual

         a
         b
        +c
        +d

Example code: (see https://github.com/felixrabe/mocha-chai-string-diff/blob/master/test/test.js for the complete example code, run with `mocha`)

    it('should compare strings (raw)', function() {
      var err = new Error('bad stuff');
      err.expected = 'a\nb\nc\nd';
      err.actual = 'a\nb\n';
      err.showDiff = true;  // breaks string diffs
      // err.showDiff = false;  // string diffs are fine
      throw err;
    });

With Chai:

    var expect = require('chai').expect;

    it('should compare strings (chai)', function() {
      try {
        expect('a\nb\n').to.equal('a\nb\nc\nd');
      } catch (err) {
        // string diffs broken because err.showDiff === true
        // err.showDiff = false;  // string diffs are fine
        throw err;
      }
    });

If you uncomment the `// err.showDiff = false;` lines (ie. if you set `showDiff` to `false`), string diffs show up fine.

**Comment by slang800** [comment]
tried out v2.1.0 & this is still broken

**Comment by a8m** [comment]
Fixed in **v2.2.3**

**Comment by caseywebdev** [comment]
Is this really fixed? If anything it looks like [the specs were changed to expect the wrong thing](https://github.com/a8m/mocha/blob/73e49676cc9200292fd5eabd80616130d7a9cf68/test/reporters/base.js#L105). Is anyone else still having this issue in 2.2.4?

**Comment by a8m** [comment]
> Is this really fixed?

yes, you can play it yourself @caseywebdev
thx

**Comment by caseywebdev** [comment]
I don't think it's working correctly (v2.2.4).

Given this test

```js
it('displays line diffs', function () {
  var err = new Error('The Error Message');
  err.expected = 'foo\nbar\nbuz\nbaz';
  err.actual = 'foo\nbar\n';
  throw err;
});
```

the reporter yields

```
  1) displays line diffs

  0 passing (11ms)
  1 failing

  1)  displays line diffs:

      Error: The Error Message
      + expected - actual

      +"foo\nbar\nbuz\nbaz"
      -"foo\nbar\n"

      at Context.<anonymous> (test/test.js:2:13)
```

The line diffs are far more useful than the diff of the JSON.stringified string...

Running the same test with my patch above yields

```
 1) displays line diffs

  0 passing (11ms)
  1 failing

  1)  displays line diffs:

      Error: The Error Message
      + expected - actual

       foo
       bar
      +buz
      +baz

      at Context.<anonymous> (test/test.js:7:13)
```

**Comment by a8m** [comment]
I don't get what's the problem, you want this string as a "raw data".

**Comment by domenic** [comment]
No we dont, we want it back like it was in 1.21.

**Comment by caseywebdev** [comment]
Look at the original post by @felixrabe. He clearly wants the line diff because it's far more readable.

**Comment by a8m** [comment]
Iet me test 1.2.1
>  He clearly wants the line diff because it's far more readable.

my bad, I'm on it.

**Comment by danielstjules** [comment]
For those who come across this issue, it has been fixed, and regression tests exist for the behavior now :)

``` javascript
$ cat test.js
it('should compare strings (raw)', function() {
  var err = new Error('bad stuff');
  err.expected = 'a\nb\nc\nd';
  err.actual = 'a\nb\n';
  err.showDiff = true;
  throw err;
});

it('displays line diffs', function () {
  var err = new Error('The Error Message');
  err.expected = 'foo\nbar\nbuz\nbaz';
  err.actual = 'foo\nbar\n';
  throw err;
});

$ mocha --version
2.2.5

$ mocha test.js


  1) should compare strings (raw)
  2) displays line diffs

  0 passing (12ms)
  2 failing

  1)  should compare strings (raw):

      Error: bad stuff
      + expected - actual

       a
       b
      +c
      +d

      at Context.<anonymous> (test.js:2:13)

  2)  displays line diffs:

      Error: The Error Message
      + expected - actual

       foo
       bar
      +buz
      +baz

      at Context.<anonymous> (test.js:10:13)
```
