### ISSUE TITLE
Mocha reports the wrong message for a before() failure

### ISSUE THREAD

**Issue by jdmarshall** [mochajs/mocha#2134]
With nested test suites, a failure will be reported for the last 'it' clause that ran, regardless of whether it has any relationship to the before() that caused the failure.

```
it('does something or other', function() {
    // Do something or other
});

describe('Outer suite', function() {
    before(function() {
        throw new Error("Something went wrong");
    });

    describe('when nothing goes wrong', function() {
        before(function() {
            //...
        });
        it('should have done something interesting', function() {
            //Do something interesting.
        });
    });
});
```

Expected behavior:  
    "before all" hook for "should have done something interesting"

Actual behavior:  
    "before all" hook for "does something or other"

**Comment by mekdev** [comment]
We are seeing the same too and it does not have to be a nested suite, just something that runs sequential. See below

File: **a.js** 
```
'use strict';
describe('Suite A', function() {
    before(function () {
        console.log('before A')
    });

    it('A should do something', function*() {
        console.log('Test A')
    });

});
```


File **b.js**

```
'use strict';
describe('Suite B', function() {

    before(function () {
        console.log('before B')
        throw new Error("Something went wrong in before B");
    });

    it('B should do something', function*() {
        console.log('Test B')
    });
});
```

File: **test.js**

```
require('./a.js');
require('./b.js');
```

Result 

```
 mstittri@mstittri-osx node_modules/.bin/_mocha test/test.js


  Suite A
before A
Test A
    ✓ A should do something

  Suite B
before B
    1) "before all" hook for "A should do something"


  1 passing (13ms)
  1 failing

  1) Suite B "before all" hook for "A should do something":
     Error: Something went wrong in before B
      at Context.<anonymous> (/.../test/b.js:7:15)
      at callFn (/.../node_modules/mocha/lib/runnable.js:286:21)
      at Hook.Runnable.run (/.../node_modules/mocha/lib/runnable.js:279:7)
      at Hook.Runnable.run (/.../node_modules/co-mocha/lib/co-mocha.js:43:16)
      at next (/.../node_modules/mocha/lib/runner.js:297:10)
      at Immediate._onImmediate (/.../node_modules/mocha/lib/runner.js:319:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)
```

The correct behavior should be 

```
 1) "before all" hook for "Suite B"
```

Or something that would point user to B.js not A.js

**Comment by mekdev** [comment]
So there is a workaround, you can name your before hook to be more descriptive like this and it will include the hook name but it will still point to the wrong test (previous test) 

```
'use strict';
describe('Suite B', function() {
    
    before(this.title ,function() {
        console.log('before B')
        throw new Error("Something went wrong in before B");
    });
});
```

You will get 

```
  Suite A
before A
Test A
    ✓ A should do something

  Suite B
before B
    1) "before all" hook: Suite B for "A should do something"


  1 passing (14ms)
  1 failing

  1) Suite B "before all" hook: Suite B for "A should do something":
```

**Comment by mekdev** [comment]
Guys it seems like this is fixed with -- https://github.com/mochajs/mocha/pull/2028

Retested again after upgrading to the latest version 2.4.5

{code}
  Suite A
before A
Test A
    ✓ A should do something

  Suite B
before B
    1) "before all" hook


  1 passing (61ms)
  1 failing

  1) Suite B "before all" hook:
     Error: Something went wrong in before B
      at Context.<anonymous> (b.js:7:15)
      at callFn (/.../node_modules/mocha/lib/runnable.js:315:21)
      at Hook.Runnable.run (/.../node_modules/mocha/lib/runnable.js:308:7)
      at Hook.Runnable.run (/.../node_modules/co-mocha/lib/co-mocha.js:43:16)
      at next (/.../node_modules/mocha/lib/runner.js:298:10)
      at Immediate._onImmediate (/.../node_modules/mocha/lib/runner.js:320:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)
{code}

cc @jdmarshall

**Comment by jdmarshall** [comment]
I am in fact seeing this problem with 2.4.5

You sure about that version number?  I'd be happy if 'upgrade' were the solution.

**Comment by mekdev** [comment]
@jdmarshall this is what i have in package.json 

```
  "devDependencies": {
    "babel-plugin-transform-runtime": "6.6.0",
    "babel-preset-es2015": "6.6.0",
    "babel-register": "6.7.2",
    "chai": "3.0.0",
    "co-mocha": "1.1.2",
    "jayschema": "0.3.1",
    "key-del": "1.2.3",
    "lodash": "4.5.1",
    "mocha": "2.4.5",
```

**Comment by jdmarshall** [comment]
It looks like the behavior improves in 2.4.5, but yes, nested before() still fails the old way.

**Comment by jdmarshall** [comment]
I'm still trying to figure out if I can do my own PR request for this, but if someone faster than me wants to take a look, I've tracked it as far as Runner.prototype.failHook seeing ctx.currentTest when there is no currentTest.  

Looking at Runner.prototype.hook, there are a couple ways out of the function where the `delete` call is missed.  I don't have a repro case and a test for it yet.

**Comment by justincy** [comment]
In 2.4.5 I'm experiencing similar behavior where an error in a test is being reported as an error in the before hook. Rolling back to 2.3.0 solved the issue for me. I didn't try any other versions.

**Comment by ScottFreeCode** [comment]
The situation should be improved in 2.5.x; as far as I can tell, there should only be a problem now if Mocha errors internally during handling of a pending test (#2220). Can anyone who's had trouble with this issue confirm that it's fixed in general now?

**Comment by jdmarshall** [comment]
One thing I'm noticing is that the test suite for beforeEach is substantially more robust than the suite for before.  It may be that there are situations that stabilize quickly with beforeEach() that stay broken with before().

**Comment by ORESoftware** [comment]
For the OP, it's a lot easier to parse the problem with simpler names

```
it('A', function() {
  // Do something or other
});

describe('Outer suite', function() {
  before(function() {
    throw new Error("Something went wrong");
  });

  describe('Inner suite', function() {
    before(function() {
      //...
    });
    it('B', function() {
      //Do something interesting.
    });
  });
});
```
