### ISSUE TITLE
🐛 Bug: Unable to terminate long running tests

### ISSUE THREAD

**Issue by segrey** [mochajs/mocha#3570]
### Prerequisites

- [x] Checked that your issue hasn't already been filed by cross-referencing [issues with the `faq` label](https://github.com/mochajs/mocha/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Afaq%20)
- [x] Checked next-gen ES issues and syntax problems by using the same environment and/or transpiler configuration without Mocha to ensure it isn't just a feature that actually isn't supported in the environment in question or a bug in your code.
- [x] 'Smoke tested' the code to be tested by running it outside the real test suite to get a better sense of whether the problem is in the code under test, your usage of Mocha, or Mocha itself
- [x] Ensured that there is no discrepancy between the locally and globally installed versions of Mocha. You can find them with: `node node_modules/.bin/mocha --version`(Local) and `mocha --version`(Global). We recommend avoiding the use of globally installed Mocha.

### Description

Unable to terminate tests manually, e.g via Ctrl+C when running tests in a terminal.

### Steps to Reproduce

1. Create
```javascript
it('should run 10 seconds', function (done) {
  setTimeout(done, 10000);
});
```
2. Run with `mocha --timeout 1000000 test.js`
3. Do not wait until the test finishes and press Ctrl+C to terminate it.

**Expected behavior:** The test is terminated.

**Actual behavior:** The test is still running.

**Reproduces how often:** Always

### Versions

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`: 5.2.0 and 5.2.0
- The output of `node --version`: v10.13.0
- The version and architecture of your operating system: Linux 64-bit, 3.19.0-32-generic
- Your shell (bash, zsh, PowerShell, cmd, etc.): bash
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by plroebuck** [comment]
[WOMM](https://blog.codinghorror.com/content/images/uploads/2007/03/6a0120a85dcdae970b0128776ff992970c-pi.png)...
```bash
$ bin/_mocha --timeout 1000000 /tmp/test.js; echo $?
^C
130
$
```

**OS:** macOS 10.13.6
**Node:** v10.13.0
**Mocha:** 5.2.0 (cfb1182)  # modified trunk version, but changes unrelated to your issue

**Comment by segrey** [comment]
@plroebuck Please run it with `time`:
```
time ./node_modules/mocha/bin/_mocha --timeout 10000000 test.js ; echo $?


^C  ✓ should run 10 seconds (10010ms)

  1 passing (10s)


real	0m10.107s
user	0m0.084s
sys	0m0.020s
130
```

**Comment by plroebuck** [comment]
```bash
$ time bin/_mocha --timeout 1000000 /tmp/test.js; echo $?
^C

real	0m1.989s
user	0m0.116s
sys	0m0.042s
130
$
```

**Comment by segrey** [comment]
@plroebuck How can I checkout your mocha version?
```
$ git checkout cfb1182c172e43effa3011f4ab620e4935f621e9
fatal: reference is not a tree: cfb1182c172e43effa3011f4ab620e4935f621e9
```


Same issue on Mac for me
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75

$ node --version
v10.13.0
$ ./node_modules/mocha/bin/_mocha --version
5.2.0
$ time ./node_modules/mocha/bin/_mocha --timeout 1000000 /tmp/test.js ; echo $?


^C^C^C  ✓ should run 10 seconds (10005ms)

  1 passing (10s)


real	0m10.151s
user	0m0.122s
sys	0m0.025s
130
```

Could you please try to repro using mocha 5.2.0 from npm?

**Comment by outsideris** [comment]
In my local with d60b3339ffe79fadcaad22047dd20334cd77babb , I can reproduce it.

```
time bin/_mocha --timeout 1000000 test.js ; echo $?


^C  ✓ should run 10 seconds (10004ms)

  1 passing (10s)


real	0m10.199s
user	0m0.178s
sys	0m0.036s
130
```

```
time bin/mocha --timeout 1000000 test.js ; echo $?
hfoehfoe


^CTerminated: 15

real	0m0.606s
user	0m0.228s
sys	0m0.050s
143
```

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.1
BuildVersion:	18B75

$ node -v
v10.11.0

$ ./bin/mocha --version
5.2.0
```

**Comment by segrey** [comment]
@outsideris Thanks for confirming. Right, `bin/_mocha` should be used, not `bin/mocha`, I wasn't clear enough about it in the description.

Guys, any idea on ideal SIGINT handling? Maybe something like: on the first SIGINT received, keep the current behavior, and if test is still running after N seconds (say N=2), disable SIGINT handler and resend SIGINT?

**Comment by boneskull** [comment]
I think I've fixed this (somehow) in #3556, as I can't reproduce in my branch.

**Comment by boneskull** [comment]
Can someone pull `master` and see if they can reproduce this?

**Comment by Jayasankar-m** [comment]
Issue exists when using 'bin\_mocha'..
works fine with 'bin\mocha'.

**Comment by boneskull** [comment]
I'm not sure it's even necessary to do this if it works with `bin/mocha`.  

The use cases of executing `bin/_mocha` directly are limited; I see this typically used as a workaround dumb debuggers that don't understand child processes.

@segrey Would it be possible for you to pull down `master` and see if it's working for you?  

If so, I think maybe we shouldn't mess with this unless someone is complaining about `bin/_mocha` doing the wrong thing.  This is touchy code and difficult to test, so I'm loathe to change it without a good reason.

**Comment by segrey** [comment]
>Would it be possible for you to pull down master and see if it's working for you?

@boneskull The issue is still reproduced for me with the current master (9b7a28202c2813fc061abc939d15ea3e759fe0de).

>I'm not sure it's even necessary to do this if it works with `bin/mocha`.

It works with `bin/mocha` because of [`proc.kill('SIGTERM')`](https://github.com/mochajs/mocha/blob/b5c0fb0a26ee9f8fd574e78732a2cf715d7ab6ca/bin/mocha#L114): `bin/_mocha` doesn't handle `SIGTERM` and exits forcibly. Thus, currently `SIGINT` handling in `bin/_mocha` does effectively nothing.

Node.js debugger in IntelliJ IDEs 2018.3 supports debugging child processes via `NODE_OPTIONS` environment variable, however it still supports passing `--inspect-brk=<port>` to node. Since debugging is implemented in a generic way it always passes `--inspect-brk=<port>` as a node option:
```
node --inspect-brk=<port> app-main-entry-file.js app-arg1 ... app-argN
```
To support `./bin/mocha` as a main entry file, command line combining should be changed to
```
node ./bin/mocha --inspect-brk=<port> app-main-entry-file.js app-arg1 ... app-argN
```
Sure, it can be done for mocha specially, but it works OK with `bin/_mocha`. Unsure, it's worth doing unless `bin/_mocha` will be deprecated. Maybe, on contrary, it'd be better to support the standard debugging workflow for mocha tests when `--inspect-brk/--inspect/etc.` are passed as node options: `node --inspect-brk=<port> ./bin/mocha`? Given it's a standard way to debug any node app, perhaps users who debug mocha manually for the first time, run it like that and fail.

**Comment by JoshuaKGoldberg** [comment]
I don't reproduce this - so looks like #3556 did fix it! Yay! 🎉 

If anybody is still seeing this bug, please do file a new issue with one of our new issue templates. They'll prompt for the info we'd need to re-triage. Cheers all! 🤎
