### ISSUE TITLE
Mocha failing when error message too big

### ISSUE THREAD

**Issue by furstenheim** [mochajs/mocha#3675]
### Description

Mocha never ends with big error messages

### Steps to Reproduce

```
const {expect} = require('chai')
 it('Test failing', function () {
      const longArray = _.times(10000, function (i) {
        return {a : i}
      })
      const shortArray = []
      expect(longArray).deep.equal(shortArray)
})
```

Then execute `yarn mocha test --exit`, the test will execute it will be marked as failure, but the summary will never appear and the process will not exit.

If on contrary one writes:

```
const {expect} = require('chai')
 it('Test failing', function () {
      const longArray = _.times(10000, function (i) {
        return {a : i}
      })
      const shortArray = []
      try {
        expect(longArray).deep.equal(shortArray)
     } catch (e) {
        console.error(e)
        throw new Error('Small error')
     }
})
```

The test fails and it displays an error in the summary. Error is logged without any problem.

**Expected behavior:** [What you expect to happen]
Mocha should be able to exit the process even if the error is overly long. Maybe the message could be reduced?

**Actual behavior:** [What actually happens]
The process hangs forever

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always
### Versions
Mocha 5.1.1

- The output of `mocha --version` and `node node_modules/.bin/mocha --version`:
- The output of `node --version`:
v8.11.2
- The version and architecture of your operating system:
Ubuntu
- Your shell (bash, zsh, PowerShell, cmd, etc.):
bash
- Your browser and version (if running browser tests):
- Any other third party Mocha related modules (with versions):
- The code transpiler being used:

**Comment by boneskull** [comment]
Please retry this but use the built in `assert` module. same result? if so, the problem may be in our diff-generating code. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by plroebuck** [comment]
If it just takes a long time, is that necessarily a _"confirmed bug"_?

**Comment by outsideris** [comment]
Because it doesn't take so long without mocha. 
So, I thought there is a performance issue in mocha even if I didn't find why.

**Comment by cyjake** [comment]
@furstenheim Try running mocha again with `--full-trace` enabled, if it performs well then it sure is related to #3686

**Comment by furstenheim** [comment]
@cyjake Just tried mocha 5.2.0 (latest) with `--full-trace` option and the problem persists

**Comment by cyjake** [comment]
@boneskull I've reproduced this issue locally and done a superficial study of the reason. It is blocked at `Base.epilogue()` (`generateDiff()` specifically).

**Comment by juergba** [comment]
When run in Node without Mocha, the AssertionError output appears very fast and is even shortened, see "Lines skipped".

When run in Mocha there is an additional part, which is not shortened and takes very long. The information content is the same in both parts. I will investigate, maybe we can just skip it. Or do Browsers need that second part?

```
      AssertionError [ERR_ASSERTION]: Input A expected to strictly deep-equal input B:
+ expected - actual ... Lines skipped

- [
-   {
-     a: 1
-   },
              //  [...]
-   {
-     a: 6
-   },
-   {
...
+ []
...
      + expected - actual         // additional Mocha part

      -[
      -  {
      -    "a": 1
      -  }
      -  {
```

**Comment by juergba** [comment]
The first part is read from `err.message`, an `AssertionError` of the built in `assert` module. The output is perfectly formatted and shortened. Unfortunately we can not take this formatted diff for granted with all third party assertion libraries.

The second part is made by Mocha and has to be shortened somehow. Running Mocha with `no-diff` option, the performance is very fast, since no Mocha diff is created.

**Comment by juergba** [comment]
Mocha is using [jsdiff](https://github.com/kpdecker/jsdiff) for creating a diff-patch out off `err.actual` and `err.expected`. Since several years there have been open issues regarding heavy performance problems with large files. Maybe we should think about evaluating another package one day.

For now I propose to just shorten the two strings to be compared before creating the diff-patch.
```js
var generateDiff = (exports.generateDiff = function(actual, expected) {
  var diffSize = 4096;
  if (actual.length > diffSize) {
    actual = actual.substring(0, diffSize) + ' ... Lines skipped';
  }
  if (expected.length > diffSize) {
    expected = expected.substring(0, diffSize) + ' ... Lines skipped';
  }
  return exports.inlineDiffs
    ? inlineDiff(actual, expected)
    : unifiedDiff(actual, expected);
});
```
@furstenheim Do you have time to patch `base.js` and give it a try with your `chai` example, please?

**Comment by furstenheim** [comment]
@juergba checked. That change does the trick

**Comment by plroebuck** [comment]
Does upgrading our ['jsdiff'](https://github.com/kpdecker/jsdiff/releases) dependency make any difference (before making changes to Mocha)?

**Comment by juergba** [comment]
No, doesn't make any difference.
A nice solution would be using an option like `diff-timeout` to limit the time spent in building the diff, like Google's [diff-match-patch](https://github.com/google/diff-match-patch/wiki/API) offers. 
But there is no sense in making a PR which is ignored to death then.

**Comment by wnghdcjfe** [comment]
I think this is related to the chai module, 
when `deep.equal` occur the error
and i analyze chai's equal. and 
https://www.npmjs.com/package/deep-eql
This is relevant. What do you think?

**Comment by wnghdcjfe** [comment]
I agreed to @juergba 
in lib/reporters/base.js
```
  var msg = diff.createPatch('string', actual, expected); 
  var lines = msg.split('\n').splice(5);
```
this code spent a lot of time in test code

**Comment by wnghdcjfe** [comment]
I fixed it!
in my mocha
```
const {expect} = require('chai')
const _ = require('lodash')
it('Test failing', function () {
    const longArray = _.times(10000, function (i) {
      return {a : i}
    })
    const shortArray = []
    expect(longArray).deep.equal(shortArray)
})
```
the test code spend a time like this 
real    0m1.657s
user    0m0.878s
sys     0m0.119s

I'm going to clean up my code and do PR. Thanks

**Comment by wnghdcjfe** [comment]
@juergba 
I was wrong.. sorry.the reason is all about the jsdiff

1. I loged and write file as          
# in reporters/base.js
```js
fs.writeFileSync('./message.txt', err.actual);
```
2. 
and.. 
```js
const diff = require('diff')
const _ = require('lodash') 
const fs = require('fs') 
const expected = '[]'
const actual = fs.readFileSync('./message.txt').toString(); 
console.log(actual)
var msg = diff.createPatch('string', actual, expected) 
console.log(msg) 
```
but jsdiff can't handle `"a": 9789\n  }\n  {\n    "a": 9790\n  }\n` ....
I'm sorry to confuse you.

**Comment by kevinoid** [comment]
I just ran into this issue due to large and difficult to diff `err.actual` and `err.expected` objects:

```js
const assert = require('assert');
const zlib = require('zlib');
it('produces a large/slow diff', () => { 
  assert.deepStrictEqual(new zlib.Gzip(), new zlib.Inflate());
});
```

I killed mocha after 10 minutes.  Inspector showed the following stack trace:

    at execEditLength (/tmp/example/node_modules/diff/lib/diff/base.js:53:7)
    at Diff.diff (/tmp/example/node_modules/diff/lib/diff/base.js:116:19)
    at diffLines (/tmp/example/node_modules/diff/lib/diff/line.js:44:19)
    at structuredPatch (/tmp/example/node_modules/diff/lib/patch/create.js:20:83)
    at createTwoFilesPatch (/tmp/example/node_modules/diff/lib/patch/create.js:126:14)
    at Object.createPatch (/tmp/example/node_modules/diff/lib/patch/create.js:146:10)
    at unifiedDiff (/tmp/example/node_modules/mocha/lib/reporters/base.js:449:18)
    at exports.generateDiff (/tmp/example/node_modules/mocha/lib/reporters/base.js:188:9)
    at /tmp/example/node_modules/mocha/lib/reporters/base.js:263:14
    at Array.forEach (<anonymous>)
    at Function.exports.list (/tmp/example/node_modules/mocha/lib/reporters/base.js:212:12)
    at Spec.Base.epilogue (/tmp/example/node_modules/mocha/lib/reporters/base.js:364:10)
    at Object.onceWrapper (events.js:286:20)
    at Runner.emit (events.js:203:15)
    at /tmp/example/node_modules/mocha/lib/runner.js:908:12
    at /tmp/example/node_modules/mocha/lib/runner.js:779:7
    at next (/tmp/example/node_modules/mocha/lib/runner.js:362:14)
    at Immediate._onImmediate (/tmp/example/node_modules/mocha/lib/runner.js:428:5)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

with `actual.length === 107108` and `expected.length === 115195`.

> Mocha is using [jsdiff](https://github.com/kpdecker/jsdiff) for creating a diff-patch out off `err.actual` and `err.expected`. Since several years there have been open issues regarding heavy performance problems with large files. Maybe we should think about evaluating another package one day.

Apparently Google's `diff-match-patch` compares favorably.  (See kpdecker/jsdiff#239).

You may also want to consider limiting the size of the input to diff.  Finding a minimal diff of 2 highly-dissimilar multi-MB strings is probably not a good use of time/compute/output screen space, even with a fast algorithm.  It could also be an easy interim fix until diff alternatives are evaluated.

**Comment by boneskull** [comment]
I would like to see this move forward, as we are still getting issues relating to it.

**Comment by boneskull** [comment]
it has issues from top to bottom -- from the stringification code to the diffing of those canonical results... yuk.
