### ISSUE TITLE
Re-emit the unhandledReject event

### ISSUE THREAD

**Issue by Xiaosha61** [mochajs/mocha#4743]
https://github.com/mochajs/mocha/blob/bbf0c11b29544de91a18c1bd667c975ee44b7c90/lib/runner.js#L204

What is the use case for this code here?
I got surprised by seeing the handler executed twice whenever rejecting a promise. For example
```
        Promise.reject('nobody handles me 😈 '); // reject once
        process.on('unhandledRejection', (reason, promise) => {
            console.log(' Rejection ', reason, JSON.stringify(promise)); // this shows up twice
        });
```

I notice the handler was removed(line 198) before the rejection is emitted internally in mocha, but the event seems to be cached, which means the internal emit will trigger the handler to be called anyway right after it is added back (line 206).

Is it intended to be so (what is the use case if this is true) or it is some bug?

**Comment by jedwards1211** [comment]
@mark-wiemer I just ran into this.  The code thinks what it's doing is:

1. Remove its own `unhandledRejection` listener
2. Re-emit the `unhandledRejection` event, so any other listeners get called or process crashes
3. Add back is own `unhandledRejection` listener

The problem is `emit` doesn't synchronously dispatch the event, it enqueues it and listeners get called on a later tick.  So what actually happens is an infinite event loop:

**Tick 1**
- Node dispatches an `unhandledRejection` event to registered listeners
- Mocha's `unhandledRejection` listener:
  - Removes itself from the listener list
  - calls `emit('unhandledRejection', ...)`
    - Node enqueues the event for later
  - Adds itself back to the listener list

**Tick 2 (sometime later)**
- Node dispatches the newly enqueued `unhandledRejection` event to registered listeners
  -> infinite event loop, calls Mocha's `unhandledRejection` listener again

**Comment by jedwards1211** [comment]
@mark-wiemer sorry, I was confidently incorrect there, according to the docs and behavior I'm seeing in testing `emit()` is synchronous...

I think the actual issue may be if two Mocha runners are listening to `unhandledRejection` some reason (need to find out why this was the case in my project, maybe the listeners aren't getting removed when a Mocha instance is disposed?), then their re-emitted events will trigger each other.

**Comment by jedwards1211** [comment]
Okay looking at `runner.js` it doesn't remove its listener on run end.

There is this code in `worker.js`:

```js
    mocha.run((result) => {
      // Runner adds these; if we don't remove them, we'll get a leak.
      process.removeAllListeners("uncaughtException");
      process.removeAllListeners("unhandledRejection");
```
Not sure this is a good idea either, but in any case watch serial mode doesn't seem to be doing this.

**Comment by jedwards1211** [comment]
Well, actually, `runner.dispose()` does remove all of its process listeners.  Argh.  Sure isn't easy to tell why this issue is happening in my project.

In any case, this issue is guaranteed to occur if there are simultaneous Mocha runners in the same process (possible with the programmatic API if nothing else) so we should fix it.  We could do this to prevent the event loop:

```js
  debug(
    "trapped unhandled rejection from (probably) user code; re-emitting on process",
  );
  this._removeEventListener(
    process,
    "unhandledRejection",
    this.unhandled,
  );
  if (!reemitScheduled) { // global variable to prevent other runners from emitting a duplicate 
    reemitScheduled = true;
    setTimeout(() => {
      process.emit("unhandledRejection", reason, promise);
      reemitScheduled = false;
    }, 0);
  }
  setTimeout(() => {
    if (this.state === constants.STATE_RUNNING) { // not 100% sure if root runner could be in other states
      this._addEventListener(
        process,
        "unhandledRejection",
        this.unhandled,
      );
    }
  }, 2);
```

**Comment by mark-wiemer** [comment]
Thanks for the updates, and it's good to know that this is still happening. Can you confirm whether you're seeing this on main branch (if so, what commit?), Mocha 11.7.x (please fill in the `x`), or somewhere else?

Again, yet another reminder that we maintainers are a bit low capacity at the moment, so I appreciate your patience here :)

**Comment by jedwards1211** [comment]
I may have just been getting repeated unhandled EMFILE errors and misinterpreted that as an infinite event loop... But, I think I could write a test case that triggers this by running two Mocha runners simultaneously, want me to do that?

**Comment by mark-wiemer** [comment]
You are always welcome to create detailed repros for issues you think are active! They help a ton :)

**Comment by jedwards1211** [comment]
Okay I was wrong again, even two simultaneous runners can't cause a loop as far as I can tell.

One thing that's not great about mocha's behavior here though is, if the user does have an `unhandledRejection` listener, it will be called twice with the rejection due to mocha's listener re-emitting it.

We could have mocha look at `process.listeners('unhandledRejection')`, and only re-emit if there are none outside of mocha's own listeners, so that if the user has a listener it will only be called once.

**Comment by mark-wiemer** [comment]
Rereading the initial bug report from 2021, it seems like this only happens when users add these listeners? That's not something I've ever done as a user, so I'm not sure how common this is. Of course, I'd love to fix it, I just need a feel for where this sits in priority, and it seems very low-impact. Am I missing something?

Thanks for continuing to follow up, and I'm happy to review PRs around this, but if I'm writing code myself, this bug doesn't seem high priority to me right now.

**Comment by jedwards1211** [comment]
I think you're right, I totally misinterpreted what was happening when I was watching too many files and getting tons of unhandled EMFILE errors

And yes, I think just a minor issue too
